"use client";
import { AnimatePresence, motion } from "motion/react";
import Head from "next/head";
import { useCallback, useEffect, useRef, useState } from "react";
import { io, type Socket } from "socket.io-client";
import HeadToHeadCard from "@/components/duel-card";
import BattleRoyalCard from "@/components/game-cards/battle-royale-card";
import RaceCard from "@/components/game-cards/race-card";
import BattleRoyale from "@/components/games/battle-royale";
import Race from "@/components/games/race";
import Navbar from "@/components/navigation/navbar";
import Tile from "@/components/tile";
import { env } from "@/env";
import { useAuthStore } from "@/state/auth-store";
import { useGameSessionStore } from "@/state/game-session-store";
import { useServerClockStore } from "@/state/server-clock-store";
import { createClient } from "@/utils/supabase/client";

export default function Home() {
	const [isPlaying, setIsPlaying] = useState(false);
	const [isPlayingRace, setIsPlayingRace] = useState(false);
	const [raceToken, setRaceToken] = useState<string | undefined>(undefined);
	const socketRef = useRef<Socket | null>(null);
	const user = useAuthStore((state) => state.user);
	const setRealtimeGameActive = useGameSessionStore(
		(state) => state.setRealtimeGameActive,
	);

	useEffect(() => {
		return () => {
			socketRef.current?.disconnect();
		};
	}, []);

	// Expose whether a live realtime game is in progress so app-global UI (the
	// duel notification toasts) can drop their "View duels" link while playing,
	// preventing a stray click from abandoning the match. Reset on unmount so
	// navigating away always clears the flag.
	useEffect(() => {
		setRealtimeGameActive(isPlaying || isPlayingRace);
		return () => setRealtimeGameActive(false);
	}, [isPlaying, isPlayingRace, setRealtimeGameActive]);

	const handlePlay = async () => {
		const supabase = createClient();
		const {
			data: { session },
		} = await supabase.auth.getSession();

		const accessToken = session?.access_token;
		if (!accessToken) {
			console.error("No active session found for websocket auth");
			return;
		}

		socketRef.current?.disconnect();

		const socketBaseUrl = env.NEXT_PUBLIC_WS_URL;
		const socket = io(socketBaseUrl, {
			path: "/socket.io",
			auth: {
				token: accessToken,
			},
			transports: ["websocket"],
		});

		socketRef.current = socket;

		const handleConnect = () => {
			console.log("Socket.IO connected");
			// Measure the client/server clock offset before rendering timers so
			// countdowns and life bars reflect the server's clock, not the browser's.
			void useServerClockStore.getState().sync(socket);
			setIsPlaying(true);
		};

		const handleConnectError = (error: Error) => {
			console.error("Socket.IO connection error", error.message);
			setIsPlaying(false);
		};

		const handleDisconnect = () => {
			useServerClockStore.getState().reset();
			setIsPlaying(false);
		};

		socket.on("connect", handleConnect);
		socket.on("connect_error", handleConnectError);
		socket.on("disconnect", handleDisconnect);

		return () => {
			socket.off("connect", handleConnect);
			socket.off("connect_error", handleConnectError);
			socket.off("disconnect", handleDisconnect);
		};
	};

	const handlePlayRace = async () => {
		const supabase = createClient();
		const {
			data: { session },
		} = await supabase.auth.getSession();

		const accessToken = session?.access_token;
		if (!accessToken) {
			console.error("No active session found for websocket auth");
			return;
		}

		// Race manages its own `/race` socket internally via `useRaceSocket`, so we
		// only hand it the access token rather than creating a socket here.
		setRaceToken(accessToken);
		setIsPlayingRace(true);
	};

	// Resets Race play state so the game un-mounts and the card menu returns,
	// mirroring how Battle Royale's socket `disconnect` flips `isPlaying`.
	const handleRaceLeave = useCallback(() => {
		setIsPlayingRace(false);
		setRaceToken(undefined);
	}, []);

	return (
		<>
			<Head>
				<meta content="Generated by create-t3-app" name="description" />
				<link href="/favicon_v2.png" rel="icon" />
			</Head>
			<main className="flex h-screen flex-col">
				<Navbar />
				<div className="flex min-h-0 grow flex-col items-center justify-center gap-y-5">
					<AnimatePresence>
						{!isPlaying && !isPlayingRace && (
							<motion.div
								animate={{ scale: 1 }}
								className="flex flex-col items-center gap-y-2"
								exit={{ scale: 0 }}
								initial={{ scale: 0 }}
							>
								<Tile
									revealed={true}
									size={isPlaying ? "sm" : "lg"}
									variant="correct"
									word="FINAL"
								/>
								<Tile
									revealed={true}
									size={isPlaying ? "sm" : "md"}
									variant="present"
									word="WORD"
								/>
							</motion.div>
						)}
					</AnimatePresence>
					<AnimatePresence>
						{isPlaying && user?.id ? (
							<BattleRoyale socketRef={socketRef} userId={user.id} />
						) : isPlayingRace && user?.id && raceToken ? (
							<Race
								onLeave={handleRaceLeave}
								token={raceToken}
								userId={user.id}
							/>
						) : (
							!isPlaying &&
							!isPlayingRace && (
								<div className="flex gap-x-5">
									<HeadToHeadCard />
									<BattleRoyalCard handlePlay={handlePlay} />
									<RaceCard handlePlay={handlePlayRace} />
								</div>
							)
						)}
					</AnimatePresence>
				</div>
			</main>
		</>
	);
}
