"use client";
import Head from "next/head";

import Navbar from "@/components/navigation/navbar";
import Tile from "@/components/tile";
import GameCard from "@/components/game-card";
import { useEffect, useRef, useState } from "react";
import { env } from "@/env";
import { createClient } from "@/utils/supabase/client";
import { io, type Socket } from "socket.io-client";

export default function Home() {
  const [isPlaying, setIsPlaying] = useState(false);
  const [messages, setMessages] = useState<string[]>([]);
  const socketRef = useRef<Socket | null>(null);

  const sendGuess = (word: string) => {
    const socket = socketRef.current;
    if (!socket || !socket.connected) {
      console.warn("Cannot send guess: socket is not connected");
      return;
    }

    socket.emit("guess", { word });
  };

  useEffect(() => {
    return () => {
      socketRef.current?.disconnect();
    };
  }, []);

  const handlePlay = async () => {
    const supabase = createClient();
    const {
      data: { session },
    } = await supabase.auth.getSession();

    const accessToken = session?.access_token;
    if (!accessToken) {
      console.error("No active session found for websocket auth");
      return;
    }

    socketRef.current?.disconnect();

    const socketBaseUrl = env.NEXT_PUBLIC_WS_URL.replace(/^ws/i, "http");
    const socket = io(socketBaseUrl, {
      path: "/socket.io",
      auth: {
        token: accessToken,
      },
      transports: ["websocket"],
    });

    socketRef.current = socket;

    socket.on("connect", () => {
      console.log("Socket.IO connected");
      setIsPlaying(true);
      sendGuess("BATTLE");
    });

    socket.on("guess:ack", (payload) => {
      setMessages((prev) => [...prev, JSON.stringify(payload)]);
    });

    socket.on("connect_error", (error) => {
      console.error("Socket.IO connection error", error.message);
    });

    socket.on("disconnect", () => {
      setIsPlaying(false);
    });
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta content="Generated by create-t3-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="flex flex-col h-screen">
        <Navbar />
        <div className="flex flex-col grow items-center justify-center gap-y-5">
          <div className="flex flex-col items-center gap-y-2">
            <Tile revealed={true} size="lg" word="FINAL" variant="correct" />
            <Tile revealed={true} word="WORD" size="md" variant="present" />
          </div>
          <div>
           {isPlaying ? <div>
            <button onClick={() => sendGuess("FINAL")}>TEST</button>
            {JSON.stringify(messages)}
           </div> : <GameCard
              title="Battle Royale"
              desc="100 players. One word. Last solver standing wins."
              badge="Live"
              badgeVariant="green"
              onPlay={handlePlay}
              tiles={[
                { word: "B", variant: "correct" },
                { word: "A", variant: "present" },
                { word: "T", variant: "absent" },
                { word: "T", variant: "correct" },
                { word: "L", variant: "correct" },
                { word: "E", variant: "present" },
              ]}
            />}
          </div>
        </div>
      </main>
    </>
  );
}
