"use client";
import Head from "next/head";

import Navbar from "@/components/navigation/navbar";
import Tile from "@/components/tile";
import { useEffect, useRef, useState } from "react";
import { env } from "@/env";
import { createClient } from "@/utils/supabase/client";
import { io, type Socket } from "socket.io-client";
import BattleRoyalCard from "@/components/game-cards/battle-royale-card";
import BattleRoyale from "@/components/games/battle-royale";
import { AnimatePresence } from "motion/react";
import { useAuthStore } from "@/state/auth-store";

export default function Home() {
  const [isPlaying, setIsPlaying] = useState(false);
  const socketRef = useRef<Socket | null>(null);
  const user = useAuthStore((state) => state.user);

  console.log(user);
  useEffect(() => {
    return () => {
      socketRef.current?.disconnect();
    };
  }, []);

  const handlePlay = async () => {
    const supabase = createClient();
    const {
      data: { session },
    } = await supabase.auth.getSession();

    const accessToken = session?.access_token;
    if (!accessToken) {
      console.error("No active session found for websocket auth");
      return;
    }

    socketRef.current?.disconnect();

    const socketBaseUrl = env.NEXT_PUBLIC_WS_URL;
    const socket = io(socketBaseUrl, {
      path: "/socket.io",
      auth: {
        token: accessToken,
      },
      transports: ["websocket"],
    });

    socketRef.current = socket;

    const handleConnect = () => {
      console.log("Socket.IO connected");
      setIsPlaying(true);
    };

    const handleConnectError = (error: Error) => {
      console.error("Socket.IO connection error", error.message);
      setIsPlaying(false);
    };

    const handleDisconnect = () => {
      setIsPlaying(false);
    };

    socket.on("connect", handleConnect);
    socket.on("connect_error", handleConnectError);
    socket.on("disconnect", handleDisconnect);

    return () => {
      socket.off("connect", handleConnect);
      socket.off("connect_error", handleConnectError);
      socket.off("disconnect", handleDisconnect);
    };
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta content="Generated by create-t3-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="flex flex-col h-screen">
        <Navbar />
        <div className="flex flex-col grow items-center justify-center gap-y-5">
          <div className="flex flex-col items-center gap-y-2">
            <Tile
              revealed={true}
              size={isPlaying ? "sm" : "lg"}
              word="FINAL"
              variant="correct"
            />
            <Tile
              revealed={true}
              word="WORD"
              size={isPlaying ? "sm" : "md"}
              variant="present"
            />
          </div>
          <div>
            <AnimatePresence>
              {isPlaying ? (
                <BattleRoyale socketRef={socketRef} userId={user?.id} />
              ) : (
                <div>
                  <BattleRoyalCard handlePlay={handlePlay} />
                </div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </main>
    </>
  );
}
